config/routes.rb
SearchPost::Application.routes.draw do
  resources :posts, :only => [:index, :new, :create]

end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  attr_accessible :content, :image_url, :title, :city_id, :user, :city

  define_index do
    indexes :title
    indexes :content
    indexes "'city_id_' || city_id", :as => :city_idx

    has :city_id, :type => :integer
    has :user_id, :type => :integer
    has :image_url, :type => :integer

    set_property :field_weights => {
      :title   => 2,
      :content => 1
    }
  end

  sphinx_scope :by_city do |city|
    id = city.is_a?(City) ? city.id : city
    {:conditions => {:city_idx => "city_id_#{id}"}}
  end

  sphinx_scope :with_text do |text|
    {:conditions => {:title => text, :content => text}}
  end

  sphinx_scope :group_by_city do
    {:group => 'city_id', :order => '@count desc'}
  end

  def self.loader
    Loader.new(self)
  end

  class Loader
    def initialize(klass)
      @klass = klass
      @options = {:conditions => {}}
    end

    def by_city(city)
      id = city.is_a?(City) ? city.id : city
      @options[:conditions].merge!(:city_idx => "city_id_#{id}")
      self
    end

    def with_text(text)
      @options[:conditions].merge!(:title => text, :content => text)
      self
    end

    def group_by_city
      @options[:group] = 'city_id'
      @options[:order] = '@count desc'
      self
    end

    def duplicate
      new_options = @options.dup
      clone = dup
      clone.instance_variable_set(:@options, new_options)
      clone
    end

    def result
      @options.any? ? @klass.search(@options) : @klass.search
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :find_user, :only => :create
  helper_method :query

  def new
    @post = Post.new
  end

  def create
    @post = @user.posts.build(params[:post])
    if @post.save
      redirect_to posts_url
    else
      render :new
    end
  end

  def index
    @query = params[:query]
    loader = Post.scoped
    loader.by_city(query[:city]) if query[:city].present?
    loader.with_text(query[:text]) if query[:text].present?
    @cities = loader.duplicate.group_by_city.result
    @posts = loader.result
  end

  def find_user
    @user = User.find(params[:post].delete(:user_id))
  end

  def query
    @query.blank? ? {} : @query
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SearchPost</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.haml
= link_to 'New', new_post_url
= form_tag posts_url, :method => :get do
  = select_tag 'query[city]', options_from_collection_for_select(City.all, :id, :name, query[:city]), :prompt => "Select city"
  = text_field_tag 'query[text]', query[:text]
  = submit_tag 'search'

%ul
- @cities.each_with_group_and_count do |_, city_id, count|
  %li
    .city= City.find(city_id).name
    .count= count
%ul
- @posts.each do |post|
  %li
    = image_tag post.image_url
    .city= post.city.try(:name)
    .title= post.title
    .content= post.content
    .user= post.user.try(:name)

app/views/posts/new.html.haml
= form_for @post do |f|
  = f.text_field :title
  = f.text_area :content
  = f.collection_select :city_id, City.all, :id, :name, prompt: true
  = f.collection_select :user_id, User.all, :id, :name